name: CD

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --prefix frontend

      - name: Build backend
        run: npm run build --prefix backend

      - name: Deploy to production
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
          HOST: ${{ secrets.HOST }}
        run: |
          # Add your deployment steps here
          # For example:
          # - Copy build artifacts to the production server
          # - Restart the application on the production server
          # - Run database migrations
          # - Notify team about the deployment