name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: npm ci

      - name: Build frontend
        run: npm run build --prefix frontend

      - name: Build backend
        run: npm run build --prefix backend

      - name: Run tests
        run: npm test

      - name: Lint code
        run: npm run lint

      - name: Deploy to staging
        if: github.ref == 'refs/heads/main'
        run: |
          # Add your deployment steps here
          # For example:
          # - Deploy frontend to a staging server
          # - Deploy backend to a staging server
          # - Run database migrations
          # - Notify team about the deployment